"use client";

import Link from "next/link";
import { ProductHeader } from "../../../product-components";
import { humanRoundStatus } from "../../../lib/display";
import { useCopy, useLocale } from "../../../i18n";

type Integrity = { evidenceHashValid: boolean; poolIdentityMatches: boolean; observationWindowMatches: boolean; resolvedPriceMatchesOnchain: boolean };
type Evidence = { status: "VERIFIED" | "INTEGRITY_MISMATCH"; source: string; endpoint: string; symbol: string; cadence: "DAILY" | "WEEKLY" | "QUARTERLY"; direction: "HIGH" | "LOW"; interval: string; observationWindow: { startInclusive: string; endExclusive: string }; candleCount: number; sourceDataSha256: string; rounding: string; selected: { exact: string; resolvedPriceCents: string; candleOpenTime: number; candleOpenIso: string }; evidenceSha256: string; createdAt: string; settlementTxHash: string | null; integrity: Integrity };
export type VerificationResult = { chain: { id: number; name: string; explorerUrl: string }; pool: { slug: string; poolAddress: string; asset: string; direction: "HIGH" | "LOW"; cadence: "DAILY" | "WEEKLY" | "QUARTERLY"; sourceSymbol: string }; round: { roundId: number; contractStatus: "ENTRY_OPEN" | "LOCKED" | "SETTLED" | "CANCELLED"; observationStartAt: string; observationEndAt: string; resolvedPriceCents: string; resolvedPrice: string | null }; verification: { status: "PENDING" } | { status: "NOT_APPLICABLE"; reason: string } | { status: "EVIDENCE_MISSING" | "EVIDENCE_INTEGRITY_FAILED"; reason: string } | Evidence };

function formatUsd(value: string, locale: "en" | "tr") { const n = Number(value); return Number.isFinite(n) ? new Intl.NumberFormat(locale === "tr" ? "tr-TR" : "en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n) : value; }
function formatUtcDateTime(value: string, locale: "en" | "tr") { return new Intl.DateTimeFormat(locale === "tr" ? "tr-TR" : "en-US", { timeZone: "UTC", month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value)) + " UTC"; }
function cadence(value: "DAILY" | "WEEKLY" | "QUARTERLY", locale: "en" | "tr") { return (locale === "tr" ? { DAILY: "Gün", WEEKLY: "Hafta", QUARTERLY: "Çeyrek" } : { DAILY: "Daily", WEEKLY: "Weekly", QUARTERLY: "Quarterly" })[value]; }
function direction(value: "HIGH" | "LOW", locale: "en" | "tr") { return (locale === "tr" ? { HIGH: "Yüksek", LOW: "Düşük" } : { HIGH: "High", LOW: "Low" })[value]; }

function Check({ label, valid }: { label: string; valid: boolean }) { const t = useCopy(); return <li data-valid={valid}><span>{label}</span><b>{valid ? t.verify.matches : t.verify.mismatchValue}</b></li>; }
function Unavailable({ invalid }: { invalid: boolean }) { const t = useCopy(); return <main className="ex-pools ex-proof"><ProductHeader /><div className="ex-shell ex-result__unavailable"><p className="ex-eyebrow">{t.verify.eyebrow}</p><h1 className="ex-display ex-display--md">{t.verify.unavailable}</h1>{!invalid && <p className="ex-lede">{t.verify.unavailableBody}</p>}<Link href="/pools" className="ex-pool__back">← {t.verify.backToPools}</Link></div></main>; }

export function VerifyClient({ result, invalid = false }: { result: VerificationResult | null; invalid?: boolean }) {
  const { locale } = useLocale(); const t = useCopy();
  if (!result) return <Unavailable invalid={invalid} />;
  const { pool, round, verification } = result;
  const evidence = verification.status === "VERIFIED" || verification.status === "INTEGRITY_MISMATCH" ? verification : null;
  const warning = verification.status === "EVIDENCE_MISSING" || verification.status === "EVIDENCE_INTEGRITY_FAILED" || verification.status === "INTEGRITY_MISMATCH";
  const title = verification.status === "VERIFIED" ? t.verify.verified : verification.status === "PENDING" ? t.verify.pending : verification.status === "NOT_APPLICABLE" ? t.verify.notApplicable : verification.status === "INTEGRITY_MISMATCH" ? t.verify.mismatch : t.verify.evidenceIssue;

  return <main className="ex-pools ex-proof"><ProductHeader /><div className="ex-shell">
    <Link href={`/results/${pool.slug}/${round.roundId}`} className="ex-pool__back">← {t.verify.backToResult}</Link>
    <section className="ex-proof__head" data-warning={warning}><div><p className="ex-eyebrow">{t.verify.eyebrow}</p><h1 className="ex-display ex-display--lg">{title}</h1><p className="ex-proof__identity">{pool.asset} · {cadence(pool.cadence, locale)} {direction(pool.direction, locale)} · {t.result.round} #{round.roundId}</p></div><div className="ex-proof__hero">
      {verification.status === "VERIFIED" && round.resolvedPrice && <><span>{t.verify.resolvedPrice}</span><strong className="ex-num">{formatUsd(round.resolvedPrice, locale)}</strong></>}
      {verification.status === "PENDING" && <><p>{t.verify.pendingBody}</p><dl><div><dt>{t.verify.currentStatus}</dt><dd>{humanRoundStatus(round.contractStatus, locale)}</dd></div><div><dt>{t.verify.observationEnds}</dt><dd><span suppressHydrationWarning>{formatUtcDateTime(round.observationEndAt, locale)}</span></dd></div></dl></>}
      {verification.status === "NOT_APPLICABLE" && <p>{t.verify.cancelledBody}</p>}
      {(verification.status === "EVIDENCE_MISSING" || verification.status === "EVIDENCE_INTEGRITY_FAILED") && <><p>{t.verify.evidenceIssueBody}</p><small className="ex-proof__reason">{t.verify.reason} · {verification.reason}</small></>}
      {verification.status === "INTEGRITY_MISMATCH" && <p>{t.verify.mismatchBody}</p>}
    </div></section>

    {verification.status === "PENDING" && <section className="ex-proof__pending" aria-labelledby="proof-readiness"><div className="ex-result__section-head"><div><p className="ex-eyebrow">{t.verify.readiness}</p><h2 id="proof-readiness" className="ex-display ex-display--md">{t.verify.pending}</h2></div><p>{t.verify.pendingBody}</p></div><ol className="ex-progress-rail"><li><span className="ex-progress-rail__number">01</span><div><h3>{t.verify.readinessRound}</h3><p>{t.verify.readinessRoundBody}</p><small className="ex-num">{pool.asset} · {pool.sourceSymbol} · #{round.roundId}</small></div></li><li><span className="ex-progress-rail__number">02</span><div><h3>{t.verify.readinessObservation}</h3><p className="ex-num">{formatUtcDateTime(round.observationStartAt, locale)}<br />→ {formatUtcDateTime(round.observationEndAt, locale)}</p></div></li><li><span className="ex-progress-rail__number">03</span><div><h3>{t.verify.readinessSettlement}</h3><p>{t.verify.readinessSettlementBody}</p><small>{humanRoundStatus(round.contractStatus, locale)}</small></div></li><li><span className="ex-progress-rail__number">04</span><div><h3>{t.verify.readinessVerification}</h3><p>{t.verify.readinessVerificationBody}</p></div></li></ol><dl className="ex-proof__document-meta"><div><dt>{result.chain.name}</dt><dd className="ex-num">{result.chain.id}</dd></div><div><dt>{t.verify.pool}</dt><dd className="ex-proof__code">{pool.poolAddress}</dd></div><div><dt>{t.verify.currentStatus}</dt><dd>{humanRoundStatus(round.contractStatus, locale)}</dd></div></dl></section>}

    {evidence && <><ol className="ex-proof__sequence"><li><span className="ex-proof__number">01</span><div><h2>{t.verify.source}</h2><dl><div><dt>{t.verify.symbol}</dt><dd className="ex-num">{evidence.symbol}</dd></div><div><dt>{t.verify.interval}</dt><dd className="ex-num">{evidence.interval}</dd></div><div><dt>{t.verify.endpoint}</dt><dd className="ex-proof__code">{evidence.endpoint}</dd></div></dl></div></li><li><span className="ex-proof__number">02</span><div><h2>{t.verify.window}</h2><dl><div><dt>{t.verify.observationWindow}</dt><dd><span suppressHydrationWarning>{formatUtcDateTime(evidence.observationWindow.startInclusive, locale)} → {formatUtcDateTime(evidence.observationWindow.endExclusive, locale)}</span></dd></div><div><dt>{t.verify.candles}</dt><dd className="ex-num">{evidence.candleCount}</dd></div></dl></div></li><li><span className="ex-proof__number">03</span><div><h2>{t.verify.extremum}</h2><dl><div><dt>{t.verify.selectedValue}</dt><dd className="ex-num">{evidence.selected.exact}</dd></div><div><dt>{t.verify.selectedCandle}</dt><dd className="ex-num"><span suppressHydrationWarning>{formatUtcDateTime(evidence.selected.candleOpenIso, locale)}</span></dd></div><div><dt>{t.verify.rounding}</dt><dd>{evidence.rounding}</dd></div></dl></div></li><li><span className="ex-proof__number">04</span><div><h2>{t.verify.onchain}</h2><dl><div><dt>{t.verify.pool}</dt><dd className="ex-proof__code">{pool.poolAddress}</dd></div><div><dt>{t.verify.onchainPrice}</dt><dd className="ex-num">{round.resolvedPrice ? formatUsd(round.resolvedPrice, locale) : "—"}</dd></div>{evidence.settlementTxHash && <div><dt>{t.verify.settlementTransaction}</dt><dd className="ex-proof__code">{evidence.settlementTxHash}</dd></div>}</dl></div></li><li><span className="ex-proof__number">05</span><div><h2>{t.verify.hashes}</h2><dl><div><dt>{t.verify.sourceHash}</dt><dd className="ex-proof__code">{evidence.sourceDataSha256}</dd></div><div><dt>{t.verify.evidenceHash}</dt><dd className="ex-proof__code">{evidence.evidenceSha256}</dd></div></dl></div></li></ol><section className="ex-proof__checks" data-warning={verification.status === "INTEGRITY_MISMATCH"}><div><p className="ex-eyebrow">{t.verify.integrity}</p><h2 className="ex-display ex-display--md">{verification.status === "VERIFIED" ? t.verify.verified : t.verify.mismatch}</h2></div><ul><Check label={t.verify.evidenceHash} valid={evidence.integrity.evidenceHashValid} /><Check label={t.verify.pool} valid={evidence.integrity.poolIdentityMatches} /><Check label={t.verify.observationWindow} valid={evidence.integrity.observationWindowMatches} /><Check label={t.verify.onchainPrice} valid={evidence.integrity.resolvedPriceMatchesOnchain} /></ul></section></>}
  </div></main>;
}
